#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

bspc monitor -d '' '' '' '' '' '' '' '漣' '' 

bspc config border_width         4
bspc config window_gap           10
bspc config border_radius 		 10			# And install yay -S picom-pijulius-git
bspc config split_ratio          0.50

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config pointer_follows_focus 	true
bspc config single_monocle        	false
bspc config focus_follows_pointer 	true

# Bsp-layout -- Stack Mode in workspace 1
bsp-layout set tall -- --master-size 0.5	#https://github.com/phenax/bsp-layout

# Border
bspc config focused_border_color 	"#7aa2f7"
bspc config normal_border_color  	"#32344a"
bspc config active_border_color  	"#444b6a"
bspc config presel_feedback_color 	"#7aa2f7"

# fix pointer
xsetroot -cursor_name left_ptr

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Bspc Rules
bspc rule -a Screenkey manage=off
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a Nemo desktop='^3' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a subl desktop='^4' follow=on focus=on
bspc rule -a Atril desktop='^4' follow=on focus=on
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a Gedit desktop='^4' follow=on focus=on
bspc rule -a Zathura desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on
bspc rule -a kolourpaint desktop='^5' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^5' state=floating follow=on
bspc rule -a vlc desktop='^6' state=floating follow=on focus=on
bspc rule -a mpv desktop='^6' state=floating follow=on focus=on
bspc rule -a Clementine desktop='^7' follow=on focus=on
bspc rule -a spotify desktop='^7' state=floating follow=on focus=on
bspc rule -a "VirtualBox Manager" desktop='^8' state=floating follow=on
bspc rule -a qBittorrent desktop='^8' follow=on focus=on
bspc rule -a discord desktop='^9' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^9' follow=on focus=on
bspc rule -a "Image Lounge" state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Galculator state=floating follow=on focus=on
bspc rule -a Pavucontrol state=floating follow=on focus=on
bspc rule -a Lxappearance state=floating follow=on focus=on
bspc rule -a gsimplecal state=floating follow=on focus=on
bspc rule -a Xfce4-appfinder state=floating follow=on focus=on
bspc rule -a Xfce4-appfinder --collapsed state=floating follow=on focus=on

## Autostart ##

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey 

# Set display from arandr saved script
sh ~/.screenlayout/monitors.sh &

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &  # If using polkit-gnome

# Launch keybindings daemon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -b --experimental-backends --config $HOME/.config/bspwm/picom.conf &

# Wallpaper
nitrogen --restore &

# Start udiskie
udiskie &
udisks2 &

# MPD
exec mpd &

# Keyboard
/usr/bin/numlockx on &
setxkbmap -model abnt2 -layout br -variant abnt2 &
xset led 3 &
xset s off &
xset -dpms &
